Parallels/prl-devops-service

data/users.go, main.go
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> added a method to update root password during deployment

.github/workflows/release.yml
Adding the ability to change the swagger doc version on new releases
=> adding a change to update the swagger doc version

src/startup/main.go
Moved from user/password to apikey when enabling host orchestrator. resources for authentication
=> starting to use a special api key for the self orchestrator host

helm/templates/config-map.yaml, helm/templates/deployment.yaml, helm/templates/persistent_volume.yaml, helm/templates/secrets.yaml, helm/templates/virtual-service.yaml, helm/values.yaml, src/config/main.go, src/constants/main.go, src/serviceprovider/main.go
Improving the helm chart with further configurations and adding a persistent storage
=> adding api helm improvements

helm/templates/config-map.yaml, helm/templates/deployment.yaml, helm/values.yaml, src/catalog/import.go, src/orchestrator/main.go
Fixing an issue where the catalog id needed to be case sensitive
=> fix issue with import case sensitive

src/catalog/models/catalog_manifest_provider.go
Fixed a bug where when pushing a catalog image to a remote catalog failed to generate the right url
=> further fixes to the pull

src/catalog/main.go, src/catalog/models/push_catalog_manifest.go, src/catalog/push.go, src/data/models/virtual_machine.go, src/errors/common.go, src/mappers/virtual_machine_advanced.go, src/models/virtual_machine_config.go, src/models/virtual_machines.go
Fixed some bugs found in the terraform provider
=> fixes some bugs

CHANGELOG.md, src/basecontext/api_context.go, src/basecontext/main.go
Fixed an issue where the api base context was not setting the log correctly resulting in missing log lines
=> improved logging

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml, README.md
Adding new Feature and Bug templates
=> adding templates for the issues and bugs

README.md
Reflecting the changes in agreement into the readme file for better visibility
=> add new license agreement to readme

.github/workflows/release.yml
This will fix the issue with the release pr pipeline missing files
=> fixing release issue

.github/workflows/release.yml
- fixed a typo in the release workflow that stopped the release from happening
=> fixing release pr workflow

.github/workflows/publish.yml, .github/workflows/release.yml, Dockerfile, src/basecontext/test/mock_base_context.go, src/constants/amplitude.go, src/go.mod, src/go.sum, src/orchestrator/main.go, src/serviceprovider/brew/main.go, src/serviceprovider/main.go, src/serviceprovider/system/main.go, src/startup/main.go, src/telemetry/events.go, src/telemetry/main.go, src/telemetry/main_test.go, src/telemetry/telemetry_item.go, src/telemetry/telemetry_item_test.go, src/telemetry/telemetry_service.go, src/telemetry/telemetry_service_test.go, src/telemetry/test/mock_amplitude_client.go
Initial work for implementing the telemetry for the project using the Amplitude SDK, for now we only have very basic telemetry enabled and it will be on for everyone until we release, we plan to set a way to disable this if unwanted
=> Implement amplitude telemetry

.github/workflows/publish.yml, .github/workflows/release.yml
- Fixed an issue in the workflow where the publish flow was not automatically being triggered
- Fixed an issued where the auto versioning was not changed
=> Fix issues with the auto versioning

Makefile, src/cmd/main.go, src/install/mac_plist_daemon.go
- fixing an issue with the daemon installation in Mac with the new exec name
=> fixing installation filename

src/serviceprovider/main.go, src/telemetry/main.go, src/telemetry/telemetry_item.go, src/telemetry/telemetry_item_test.go, src/telemetry/telemetry_service.go
- Improved the calculation of the user_id for telemetry as there was a chance for the user_id to be too small
=> Improved user_id to fix issue with sending telemetry

.gitignore, src/errors/diagnostic.go, src/models/orchestrator_host.go
- Fixing an issue where it was not straight forward to add an host in the orchestrator
=> Improving the orchestrator host management

docs/_includes/notification.html, docs/_includes/toc.html, docs/_sass/layout.scss, docs/examples/remote-catalog.md, src/cmd/catalog.go, src/cmd/main.go, src/pdfile/models/pdfile.go, src/pdfile/models/pdfile_test.go, src/pdfile/pull.go, src/pdfile/validation.go
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Fix pull cmd

docs/_data/download_tabs.yml, docs/_includes/inner-tabs.html, docs/docs/getting-started/installation.md, docs/examples/remote-catalog.md
- Fixed some issues with the documentation where the download links were not being rendered correctly
- Fixed some missing URLs in the documentation
- Fixed a typo on the name of the package
=> fixes to the documentation

CHANGELOG.md, helm/templates/_helpers.tpl, helm/templates/config-map.yaml, helm/templates/deployment.yaml, helm/templates/hpa.yaml, helm/templates/istio-gateway.yaml, helm/templates/persistent_volume.yaml, helm/templates/pod-disruption-budget.yaml, helm/templates/secrets.yaml, helm/templates/service.yaml, helm/templates/serviceaccount.yaml, helm/templates/virtual-service.yaml, helm/values.yaml, src/catalog/models/virtual_machine_manifest_patch.go, src/catalog/push_metadata.go, src/controllers/catalog.go, src/data/catalog.go, src/data/models/catalog_manifest.go, src/data/orchestrator.go, src/serviceprovider/system/main.go
- Added a new unified install script to be used  in mac/linux
- Added ability to add/remove tags from catalog manifests
- Added ability to add/remove roles from catalog manifests
- Added ability to add/remove claims from catalog manifests
- Fixed an issue were the executable would not read the configuration file correctly if it was on path
- Fixed an issue were we could not add two hosts with the same url and different ports
- Improved our helm chart
=> Wip 150524

CHANGELOG.md, src/restapi/common_middleware.go, src/telemetry/events.go, src/telemetry/telemetry_item.go
- Adding telemetry fix and encryption of PII
=> adding telemetry fix and encryption of PII

.github/workflows/automation.yml, docs/_includes/head.html, docs/docs/getting-started/configuration.md, src/config/main.go, src/serviceprovider/parallelsdesktop/main.go
- Fixed an issue where the background VM refresh method was not starting
- Updated documentation
=> V0.8.0 hotfix

src/main.go
fixing a problem with a calling home
=> fixing the issue with the calling home not repeating

CHANGELOG.md, README.md, docs/index.md, src/cmd/main.go, src/main.go, src/serviceprovider/main.go, src/telemetry/events.go, src/telemetry/main.go, src/telemetry/telemetry_item.go
- Fixed an issue where some missing details in telemetry would crash
- Added better readme documentation
- updated some documentation
=> v0.8.1 Hotfix

src/orchestrator/get_host_hardware_info.go, src/orchestrator/update_host.go
- fixed an issue when trying to update an orchestrator host that is offline
=> hotfix-110724-1

CHANGELOG.md, scripts/install.sh, src/catalog/models/pull_catalog_manifest.go, src/controllers/catalog.go, src/models/amplitude.go, src/pdfile/main.go, src/pdfile/models/pdfile.go, src/pdfile/processors/client_processor.go, src/pdfile/pull.go, src/pdfile/validation.go
Adding client to the pull request API
=> Adding client to pull requests for catalog

.github/workflows/pr.yml, src/controllers/catalog.go, src/pdfile/pull.go
Fixed a bug where telemetry was not been sent by the pdfile
=> enabled telemetry from pdfile pulls

CHANGELOG.md, src/main.go, src/telemetry/events.go
- Updated all event names to use the same naming convention as everything else
=> Updated the events naming convention

.vscode/launch.json, CHANGELOG.md, src/helpers/os.go
- Removed an extra debug line that existed in the code
=> fixing extra debug line

src/catalog/main.go, src/catalog/models/pull_catalog_manifest.go, src/catalog/models/push_catalog_manifest.go, src/catalog/models/virtual_machine_manifest.go, src/catalog/pull.go, src/data/models/catalog_manifest.go, src/mappers/catalog.go, src/models/catalog.go, src/pdfile/models/pull_response.go, src/pdfile/pull.go
Adding the pack size to the catalog metadata to allow the information to be showed on the API response
=> Add extra metadata to catalog

.github/workflows/pr.yml, scripts/install.sh
=> fixed the install script missing the service install

install_cfg.json, src/config/main.go, src/install/mac_plist_daemon.go, src/install/service_config.go
- Fixed the service install plist
=> fix install service method

src/cmd/help.go
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Fix a typo in help message

Makefile, src/helpers/os.go, src/helpers/volume_unix.go, src/helpers/volume_windows.go
- Fixed an issue where we would not be able to compile for windows
=> fix windows compilation error

src/catalog/import_vm.go, src/data/main.go
- Fixed an issue where the name of the catalog would be wrong when importing vms
=> Fix issue with import catalog

.github/workflows/automation.yml, .github/workflows/milestones.yml, .github/workflows/projects.yml, src/catalog/pull.go, src/models/virtual_machine_execute.go, src/serviceprovider/parallelsdesktop/main.go
- Added environment variables to the execute endpoint
- Fixed some issue with the pipeline
=> Add environment variables to execute

src/controllers/orchestrator.go, src/orchestrator/create_host_reverse_proxy_host.go, src/orchestrator/delete_host_reverse_proxy_host.go, src/orchestrator/delete_host_reverse_proxy_host_http_route.go, src/orchestrator/update_host_reverse_proxy_host.go, src/orchestrator/update_host_reverse_proxy_host_tcp_route.go
- Adds the support for an orchestrator to query the hardware endpoint of a host returning the raw data to use with terraform
=> Adds endpoint to the orchestrator to query a host hardware

src/controllers/orchestrator.go, src/data/models/host_resources.go, src/data/models/orchestrator_host.go, src/data/orchestrator.go, src/mappers/system.go, src/models/orchestrator_host.go, src/models/orchestrator_host_resource.go, src/orchestrator/get_hosts.go, src/orchestrator/get_orchestrator_resources.go, src/orchestrator/main.go, src/serviceprovider/apiclient/main.go
- Improved orchestrator timeouts
- Added system-reserved data to the orchestrator
=> Improved orchestrator timeouts

scripts/install.sh, src/catalog/push.go, src/mappers/orchestrator.go, src/models/orchestrator_host.go
- Added more information to the orchestrator hosts endpoint
- Added a fix for the push copy file
- Added a fix in the uninstall of the root service to also clear the database file
=> Added more info to orchestrator hosts

src/orchestrator/common.go
- Fix timeout for the apis and set the default to 5 hours
=> Fix timeout for the apis and set the default to 5 hours

src/catalog/cache.go, src/controllers/catalog.go, src/controllers/orchestrator.go, src/errors/main.go, src/errors/nested_error.go, src/mappers/catalog.go, src/models/api_error_response.go, src/models/catalog.go, src/orchestrator/delete_host_catalog_cache.go, src/orchestrator/get_host_catalog_cache.go
- Added the ability to control cache from the orchestrator
- improved error handling
- Improved the cached cleaning process
=> Initial work on the cache endpoints

src/data/models/virtual_machine.go
- Added the new host_url to the VM diff function to detect changes
=> Updated the vm diff

docs/_includes/head.html
- Fixed an issue where the new fonts were not being downloaded
=> fixed the header for the new fonts

docs/_data/homepage_contacts_callouts.yml
Fixing Leave Feedback - name and a link.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- [V] Documentation Change
- [V] I have performed a self-review of my own code
- [V] My changes generate no new warnings
=> Update Leave Feedback on homepage_contacts_callouts.yml 

.github/workflows/pr.yml, src/catalog/cacheservice/disk_space_unix.go, src/catalog/cacheservice/disk_space_windows.go, src/catalog/cacheservice/main.go
- Fixed the issue with the windows build
- Added a strategy to test all build targets during PR
=> fixing the windows build issue

.github/workflows/automation.yml, .github/workflows/milestones.yml, .github/workflows/pr.yml, .github/workflows/projects.yml, .github/workflows/publish.yml, .github/workflows/publish_beta.yml, .github/workflows/release.yml, Dockerfile, Makefile, docs/docs/github-actions/index.md, docs/examples/github-actions.md, prldevops.entitlements
- Added the new sign method for the pipeline
- Added the ability to sign the files locally
- Fixed an issue where containers images were not providing telemetry
- Updated some of the steps to build
=> initial changes to sign the macOS file with notify

.github/workflows/publish.yml, go.work.sum, src/catalog/cacheservice/integrity_check.go, src/catalog/cacheservice/main.go, src/catalog/models/virtual_machine_manifest.go
- Added a caching integrity check for all cache catalog
=> added integrity check to the cache for catalog

.github/workflow_scripts/get-latest-beta-changelog.sh, .github/workflows/automation.yml, .github/workflows/publish.yml, .github/workflows/publish_beta.yml
- Added a new script to add the correct changelog to the beta versions
- Added an option to keep old beta versions if needed
- Added a default version to the beta pipeline
=> Fixed further automations

src/controllers/config.go
- Fixed the detection for the default log location
=> Fixed the default log location

src/controllers/config.go, src/controllers/orchestrator.go, src/main.go, src/orchestrator/get_host_logs.go, src/orchestrator/get_host_token.go, src/orchestrator/get_host_urls.go, src/orchestrator/register_host.go, src/serviceprovider/apiclient/main.go
- Added the host logs endpoint to the orchestrator
- Added the host stream logs endpoint to the orchestrator
- Added a way to use a debug version when  running debugger
=> Add log endpoints to orchestrator

.github/workflow_scripts/remove-docker-images.sh, .github/workflows/publish_beta.yml, Makefile, go.work.sum, helm/templates/config-map.yaml, helm/templates/deployment.yaml, helm/values.yaml, src/basecontext/api_context.go, src/basecontext/main.go, src/basecontext/test/mock_base_context.go, src/controllers/config.go, src/go.mod, src/go.sum, src/main.go, src/models/system_usage.go
- Updated the helm chart with the logs variables
- implemented the new log channel streamer for the WebSocket to avoid opening the file
- Added a clean option to the beta deployment
=> Updated helm chart for logs

src/basecontext/main.go, src/config/main.go, src/constants/main.go, src/controllers/config.go, src/install/main.go, src/logs/logger.go, src/main.go, src/startup/main.go
- Fixed an issue where we would not be able to  get the version after deploy
- Fixed an issue where we would get the logs wrong in the container
- Added a new function to create log files
=> Fix log issues on deploy

src/controllers/config.go, src/logs/logger.go, src/serviceprovider/parallelsdesktop/main.go
- Fixed some bugs with log streaming
=> Fixed some bugs with log streaming

docs/docs/index.md, src/catalog/providers/aws_s3_bucket/main.go, src/compressor/decompress.go, src/constants/main.go, src/go.mod, src/go.sum, src/notifications/main.go, src/notifications/notification_message.go, src/pdfile/pull.go
- Added a better way to manage the blocks
- Incremented the bufferSize for decompression to 40mb
- Fixed a documentation issue
=> Implementing some more changes to the streamer

docs/index.md
- [v] Documentation Change
- [v] I have performed a self-review of my own code
=> Update index.md by adding the Enterprise Edition license
