Parallels/prl-devops-service

src/catalog/main.go, src/controllers/machines.go
- Added a timer to log how long a decompress task took
- Fixed an issue with the machines being started even when the var was off
=> minor fixes to the build system

src/basecontext/main.go, src/cmd/api.go, src/cmd/generate_security_key.go, src/cmd/install.go, src/cmd/main.go, src/cmd/root_password.go, src/cmd/test_providers.go, src/cmd/uninstall.go, src/constants/main.go, src/controllers/authorization.go, src/data/api_key.go, src/data/users.go, src/helpers/strings.go, src/helpers/strings_test.go, src/restapi/apikey_authorization_middleware.go, src/serviceprovider/main.go
- moved from sha256 hashing to bcrypt hashing
- added salt to the password hashing
- some small improvements in the cmd line interface
** Attention** This will break current users, including the superuser because the move for the bcrypt will break the current passwords of the users and API keys.
- For the Super User, you can use the environment variable *ROOT_PASSWORD* and set the new password. This will update the current hashing. For all other users, you will need to use the updated user and set the new password.
- For API Keys, the only way is to delete the key and recreate it. This is because the API Keys do not allow the secret to be updated
=> Security Improvements

.markdownlint.json, CHANGELOG.md, src/controllers/orchestrator.go, src/mappers/orchestrator.go, src/orchestrator/get_hosts_health_check.go, src/orchestrator/main.go, src/serviceprovider/apiclient/main.go
- added parallels calls when checking the host's health
- added the ability for the apiclient to have a timeout
- fixed a bug where a host would not show it status correctly
=> orchestrator performance

src/serviceprovider/system/main.go, src/startup/main.go, src/startup/seeds/packertemplates/macos_14_0.go
- Fixed an issue where the brew detector was not looking into the right path
- Fixed an issue where the log line for the macOs Sonoma template was wrong
- Fixed an issue where the brew log line was showing duplicated at starup
Fixes #98
=> Fix issue with brew install path

src/cmd/uninstall.go, src/config/main.go, src/constants/main.go, src/install/main.go, src/serviceprovider/main.go
-  Added a flag `--full` to uninstall to fully remove the database when uninstalling
- Changed the default installation for the database folder under root
=> Added ability to remove database on uninstall

CHANGELOG.md, src/serviceprovider/parallelsdesktop/main.go
- Fixed an issue where the hardware info would crash if only one VM was present
=> issue with get hardware info

CHANGELOG.md, helm/templates/deployment.yaml, helm/values.yaml
Adds option to source environment variables from Secret or ConfigMap ref. This allows pulling in secrets from outside of a static Helm values file in cases of using something like ExternalSecret provider or other.
=> [helm] allow sourcing env vars from secret or config maps

src/main.go
- Fixed an issue where the clone copy would not always be used
- Fixed an issue where the telemetry could generate a nil pointer issue
- Fixed an issue where the pull file would still need the provider even if not needed
- Fixed an issue where the db was being saved more often that needed
=> fixed some minor issue

Dockerfile, src/controllers/machines.go, src/data/models/host_resources.go, src/data/models/orchestrator_host.go, src/data/models/virtual_machine.go, src/data/orchestrator.go, src/mappers/orchestrator.go, src/mappers/virtual_machine.go, src/mappers/virtual_machine_network_information.go, src/models/orchestrator_host.go, src/models/system_usage.go, src/models/virtual_machine_execute.go, src/models/virtual_machine_upload.go, src/models/virtual_machines.go, src/orchestrator/main.go, src/serviceprovider/parallelsdesktop/main.go, src/serviceprovider/system/main.go
- Added the External IP Address to every virtual machine if known
- Added the Internal IP Address to every virtual machine if running
- Changed the docker image from scratch to alpine to allow for cpu and external ip address
- Added the external IP Address to the config hardware endpoint
- Added the OS name to the config hardware endpoint
- Added the OS version if available to the config hardware endpoint
- Added the new hardware fields to the orchestrator hosts endpointFixes # (issue)
resolves #224 
=> Display IP addresses when available

src/catalog/models/catalog_manifest_provider.go, src/data/models/host_resources.go, src/data/orchestrator.go, src/mappers/orchestrator.go, src/models/create_vritual_machine_specs.go, src/models/orchestrator_host.go, src/orchestrator/common.go, src/orchestrator/create_host_virtual_machine.go, src/orchestrator/get_host_virtual_machines.go, src/orchestrator/main.go
- Fixed an issue where the orchestrator would not take into account the 2 vms limitation when gathering the necessary space [fixes #229]
=> Fix issue with the applevm limitations

src/models/virtual_machine_execute.go
- Fixed a bug on the execute endpoint where it would give an error if the command was present but the script was not
=> Fix a bug on execute endpoint

src/orchestrator/create_host_virtual_machine.go, src/orchestrator/get_hosts_health_check.go, src/orchestrator/main.go
- Fixed an issue with the CPU count as it was not taking into consideration we already had reserved cpus
- Added a higher timeout to orchestrator hosts health checks
- added missing timeout in some of the orchestrator api calls
=> Fix issue with CPU Count

src/orchestrator/create_host_virtual_machine.go, src/serviceprovider/parallelsdesktop/main.go
- Fixed an issue with the CPU threshold that was added twice to the orchestrator
=> Fix an issue CPU threshold

src/config/main.go, src/constants/main.go, src/controllers/reverse_proxy.go, src/data/models/reverse_proxy.go, src/data/reverse_proxy.go, src/mappers/reverse_proxy.go, src/reverse_proxy/main.go, src/reverse_proxy/models/config.go
- Fixed an issue where the reverse proxy would fail to initialize due to prot conflict and any attempt to restart would crash
- fixed an issue where we allowed routes to be created even if the reverse proxy was disabled
- fixed an issue where if the config changes in memory we would not save those changes
- added the ability to choose the port and host trough configuration or env variables
=> Fixing the issues with the reverse proxy

src/catalog/main.go, src/cmd/test_providers.go, src/helpers/os.go
- Added the ability to extract sparce and symlinks
=> Fixed the sparse compatibility

.vscode/launch.json, src/catalog/cacheservice/main.go, src/catalog/providers/aws_s3_bucket/donotuse.go, src/catalog/providers/aws_s3_bucket/main.go, src/compressor/decompress.go, src/go.mod, src/go.sum
- Fixed an issue where the decompressor would failed to deal with symlink that did not exist
- Fixed an issue where the stream process would not catch all of the errors from the decompressor
- Moved unused code to another file until we release the version
=> Fix Decompress bug for symlink

src/main.go
- Fixed an issue where if we would set the log to file from the config.yaml it would not read it at startup
=> Fix log to file issue

src/controllers/config.go, src/go.mod, src/go.sum
- Added an endpoint to return the log file
- Added an endpoint to stream the logs using websockets
=> Added an endpoint to be able to get the logs

src/controllers/config.go, src/install/mac_plist_daemon.go, src/install/service_config.go
- added an error message if file logger is disabled
- enabled file logger by default
=> Fix controllers for log streaming

src/controllers/config.go
- Fixed an issue where we would not be able to detect the file location for the logs and therefor not stream it
=> Fix issue with detect log file for stream

.github/workflow_scripts/announce_discord.sh, src/catalog/providers/aws_s3_bucket/main.go
- Added an unstable stream for was to test speed on aws
=> unstable test for improve speed in stream

src/helpers/version.go, src/helpers/version_test.go, src/serviceprovider/parallelsdesktop/main.go
- Added the new prlcopy script if PD 20.2.0 or above, system will use 'prlcopy' binary else, system will try to compress and upload the file using exec command, Fixes #227
=> 227 - Enable the ability to upload files to VMs
